version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: feature-flags-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: feature_flags
      POSTGRES_USER: feature_flags_user
      POSTGRES_PASSWORD: feature_flags_password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
